server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ims?serverTimezone=GMT%2B8
    username: root
    password: 416527&&xzj123
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  redis:
    host: 192.168.217.133       #Redis服务器连接端口
    port: 6379
    password:                   #Redis服务器连接密码(默认为空)
    pool:
      max-active: 8             #连接池最大连接数 使用负值表示没有限制)
      max-wait: -1                #连接池最大阻塞等待时间(使用负值表示没有限制)
      max-idle: 8                  #连接池中的最大空闲连接
      min-idle: 0                #连接池中的最小空闲连接
    timeout: 30000                #连接超时时间 (毫秒)


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#配置 jwt 生成 token 的secret
jwt:
  auth:
    secret: 123456
    expired: 86400000 #毫秒
    redis:
      enable: false

logging:
  config: classpath:log/logback.xml


